import Config

db_schema = System.get_env("DB_SCHEMA") || raise "environment variable DB_SCHEMA is missing"

database_url =
  System.get_env("DATABASE_URL") ||
    raise """
    environment variable DATABASE_URL is missing.
    For example: ecto://USER:PASS@HOST/DATABASE
    """

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :vyre, VyreWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :vyre, Vyre.Repo,
  parameters: [search_path: db_schema],
  migration_default_prefix: db_schema,
  migration_source: "#{db_schema}_schema_migrations",
  url: database_url,
  ssl: [
    verify: :verify_peer,
    cacertfile: "/etc/ssl/certs/prod-ca-2021.crt",
    server_name_indication: String.to_charlist(URI.parse(System.get_env("DATABASE_URL")).host)
  ],
  pool_size: 5,
  queue_target: 5000,
  queue_interval: 5000

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Vyre.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
